Add backupinfra listing support
gardener/vscode-gardener-tools pull request #7
Opened 2019-07-30 08:47 UTC by swapnilgm

Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>

**What this PR does / why we need it**:
This PR add the support to list backupInfrastructure resources under projects.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Added support for listing BackupInfrastructure resource under project folder.
```

2019-08-03 20:05 UTC, petersutter requested changes

2019-08-03 20:05 UTC, petersutter commented on src/gardener/gardener-tree.js
>  function clusterTypes (project) {
rename to something like `projectResources`, `projectScopedResources` or maybe you have a better name.. Initially the list contained only cluster-like resources (plant, shoot) but this changed so it makes sense to also rename the function

2019-08-03 20:05 UTC, petersutter commented on src/gardener/gardener-tree.js
> +    forceDeletionEnabled: _.get(backupInfra, ['metadata', 'annotations', 'backupinfrastructure.garden.sapcloud.io/force-deletion']) || "false",
the lodash get function supports a default parameter
```suggestion
    forceDeletionEnabled: _.get(backupInfra, ['metadata', 'annotations', 'backupinfrastructure.garden.sapcloud.io/force-deletion'], "false"),
```

2019-08-03 20:05 UTC, petersutter commented on src/gardener/gardener-tree.js
>    NODE_TYPE_CLUSTER_TYPE: 'clusterType',
rename to something like `NODE_TYPE_PROJECT_RESOURCE` or `NODE_TYPE_PROJECT_SCOPED_RESOURCE`

2019-08-06 05:19 UTC, swapnilgm commented
Thanks you for the review. I have addressed your comments. PTAL.

2019-08-06 18:25 UTC, petersutter approved these changes
lgtm, ty

2019-08-06 18:41 UTC, petersutter requested changes
I saw one more thing to add as `accessReview` was not defined (see suggestion), then it will be ok. PTAL

2019-08-06 18:41 UTC, petersutter commented on src/gardener/gardener-tree.js
> +  const canIGetBackupInfras = await accessReview.canI('get', 'backupinfrastructures')
```suggestion
  const accessReview = new SelfSubjectAccessReviewClient(project.landscape.kubeconfig)
  const canIGetBackupInfras = await accessReview.canI('get', 'backupinfrastructures')
```

2019-08-07 05:55 UTC, swapnilgm commented
Done

2019-08-07 11:20 UTC, petersutter approved these changes
lgtm, ty

2019-08-07 11:20 UTC, merged